# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fa456cb7ae2ca647a3d4a7b1719e6430668c2cd2650621a0022dcb44109f514dcfe454e5352788184fbc5dde52abbec1bc7542da7fac363bf45229e942d8928

test:
  secret_key_base: f5a412a9b3354e706783b91a2b234d08413095476d197fc60cb8b871b1428cd46560a5928b106db9ea3e781271fbcf961d068ca0f1d2a5e3ddb0c50a0d3d6bd1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
